version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - ./server/.env
